on: [push]
name: Deploy to ACI

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/doran-backend:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/doran-backend:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: doran-backend
            ports: >
              80
              443
              8080
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/doran-backend:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: doran-backend
            location: 'east us'
            # Backend ENV start here
            environment-variables: >
              DB_HOST=${{ secrets.DB_HOST }}
              DB_PORT=${{ secrets.DB_PORT }}
              DB_NAME=${{ secrets.DB_NAME }}
              DB_USERNAME=${{ secrets.DB_USERNAME }}
              DB_PASSWORD=${{ secrets.DB_PASSWORD }}
              GG_SECRET=${{ secrets.GG_SECRET }}
              FB_SECRET=${{ secrets.FB_SECRET }}
              GITHUB_SECRET=${{ secrets.GH_SECRET }}
              APP_AUTH_SECRET=${{ secrets.APP_AUTH_SECRET }}
              ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}
              AUTH_REDIRECT_URI=${{ secrets.AUTH_REDIRECT_URI }}
              JWT_SECRET=${{ secrets.JWT_SECRET }}
              EMAIL=${{ secrets.EMAIL }}
              EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
              KEY_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }}